# Generated by Django 5.0.7 on 2024-08-04 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 12, 9, 7, 290695, tzinfo=datetime.timezone.utc)),
        ),
    ]
