# Generated by Django 5.0.7 on 2024-07-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='alena.example.com', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
