# Generated by Django 5.0.7 on 2024-08-04 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0002_alter_treatment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AMS.patient'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='treatment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='AMS.treatment'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
