# Generated by Django 5.0.7 on 2024-08-04 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0003_alter_feedback_patient_alter_feedback_treatment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMS.patient'),
        ),
    ]
