# Generated by Django 5.0.7 on 2024-08-04 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0004_alter_feedback_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 4, 14, 18, 5, 152256, tzinfo=datetime.timezone.utc)),
        ),
    ]
