# Generated by Django 5.0.7 on 2024-08-05 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0006_alter_treatment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 13, 16, 54, 625735, tzinfo=datetime.timezone.utc)),
        ),
    ]
